### ISSUE TITLE
RampBugFix

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#40]
I would love to see a ramp bug fix in sharptimer that is not [RampBugFix](https://github.com/Interesting-exe/CS2Fixes-RampbugFix/) because that one just sucks its tied to cs2fixes. and cs2fixes itself is just awful, and even more so when its a highly outdated version

**Comment by audiomaster99** [comment]
> I would love to see a ramp bug fix in sharptimer that is not [RampBugFix](https://github.com/Interesting-exe/CS2Fixes-RampbugFix/) because that one just sucks its tied to cs2fixes. and cs2fixes itself is just awful, and even more so when its a highly outdated version
why dont you make one yourself? "cs2fixes is awfull" ?? you know that without cs2fixes we would not have pretty much any  plugin or css framework, that is stripped version of cs2fixes to only include stuff needed for ramp bug fix

**Comment by Letaryat** [comment]
I know that I am just "hosting" the repo and don't do much here but I think that SharpTimer should be as "basic" as possible and not to try implement functions that can be easily achieve just by installing other plugin. Creating a plugin "all in one" might be problematic in the future.
+ making working and better RampBugFix is very hard thing to do. 

All being said, I will leave this issue open since @rcnoob is the one that will decide if its possible and worth his time.

**Comment by M-archand** [comment]
RampBugFix is a metamod plugin, SharpTimer is a CounterStrikeSharp plugin. There doesn't exist a way to achieve the same in CounterStrikeSharp so that is a big ask and a waste of time in my opinion, Valve should just be fixing movement.

**Comment by rcnoob** [comment]
not really in the scope of sharptimer (and it seems impossible with cs#)
